# Generated by Django 4.2.7 on 2025-11-11 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="练习标题")),
                (
                    "slug",
                    models.SlugField(
                        max_length=200, unique=True, verbose_name="URL标识"
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "简单"),
                            ("medium", "中等"),
                            ("hard", "困难"),
                        ],
                        default="easy",
                        max_length=20,
                        verbose_name="难度级别",
                    ),
                ),
                ("problem_description", models.TextField(verbose_name="问题描述")),
                (
                    "input_format",
                    models.TextField(blank=True, verbose_name="输入格式说明"),
                ),
                (
                    "output_format",
                    models.TextField(blank=True, verbose_name="输出格式说明"),
                ),
                ("constraints", models.TextField(blank=True, verbose_name="约束条件")),
                (
                    "examples",
                    models.JSONField(
                        default=list,
                        help_text='[{"input": "...", "output": "...", "explanation": "..."}]',
                        verbose_name="示例",
                    ),
                ),
                (
                    "test_cases",
                    models.JSONField(
                        default=list,
                        help_text='[{"input": "...", "output": "..."}]',
                        verbose_name="测试用例",
                    ),
                ),
                (
                    "template_code",
                    models.TextField(blank=True, verbose_name="代码模板"),
                ),
                ("solution", models.TextField(blank=True, verbose_name="参考解答")),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="用逗号分隔",
                        max_length=200,
                        verbose_name="标签",
                    ),
                ),
                (
                    "acceptance_rate",
                    models.FloatField(default=0.0, verbose_name="通过率"),
                ),
                (
                    "submit_count",
                    models.IntegerField(default=0, verbose_name="提交次数"),
                ),
                (
                    "accepted_count",
                    models.IntegerField(default=0, verbose_name="通过次数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="courses.lesson",
                        verbose_name="所属课时",
                    ),
                ),
            ],
            options={
                "verbose_name": "编程练习",
                "verbose_name_plural": "编程练习",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.TextField(verbose_name="提交代码")),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("python", "Python"),
                            ("javascript", "JavaScript"),
                            ("java", "Java"),
                        ],
                        default="python",
                        max_length=20,
                        verbose_name="编程语言",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("running", "运行中"),
                            ("accepted", "通过"),
                            ("wrong_answer", "答案错误"),
                            ("runtime_error", "运行错误"),
                            ("time_limit_exceeded", "超时"),
                            ("memory_limit_exceeded", "内存超限"),
                        ],
                        default="pending",
                        max_length=30,
                        verbose_name="运行状态",
                    ),
                ),
                (
                    "result",
                    models.JSONField(blank=True, default=dict, verbose_name="运行结果"),
                ),
                (
                    "execution_time",
                    models.IntegerField(default=0, verbose_name="执行时间(ms)"),
                ),
                (
                    "memory_used",
                    models.IntegerField(default=0, verbose_name="内存使用(KB)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="提交时间"),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="exercises.exercise",
                        verbose_name="练习",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "代码提交",
                "verbose_name_plural": "代码提交",
                "ordering": ["-created_at"],
            },
        ),
    ]
