# Generated by Django 4.2.7 on 2025-11-11 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="课程标题")),
                (
                    "slug",
                    models.SlugField(
                        max_length=200, unique=True, verbose_name="URL标识"
                    ),
                ),
                ("description", models.TextField(verbose_name="课程描述")),
                (
                    "day_range",
                    models.CharField(
                        help_text="例如: Day01-20",
                        max_length=20,
                        verbose_name="天数范围",
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, upload_to="courses/covers/", verbose_name="封面图"
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "入门"),
                            ("intermediate", "进阶"),
                            ("advanced", "高级"),
                        ],
                        default="beginner",
                        max_length=20,
                        verbose_name="难度级别",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="是否发布"),
                ),
                ("view_count", models.IntegerField(default=0, verbose_name="浏览次数")),
                ("like_count", models.IntegerField(default=0, verbose_name="点赞数")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "课程",
                "verbose_name_plural": "课程",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="CourseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="分类名称")),
                ("slug", models.SlugField(unique=True, verbose_name="URL标识")),
                ("description", models.TextField(blank=True, verbose_name="分类描述")),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "课程分类",
                "verbose_name_plural": "课程分类",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_number", models.IntegerField(verbose_name="天数")),
                ("title", models.CharField(max_length=200, verbose_name="课程标题")),
                ("slug", models.SlugField(max_length=200, verbose_name="URL标识")),
                ("content", models.TextField(verbose_name="课程内容(Markdown)")),
                ("summary", models.TextField(blank=True, verbose_name="课程摘要")),
                (
                    "code_url",
                    models.URLField(
                        blank=True, help_text="GitHub代码链接", verbose_name="代码链接"
                    ),
                ),
                ("video_url", models.URLField(blank=True, verbose_name="视频链接")),
                (
                    "estimated_time",
                    models.IntegerField(default=60, verbose_name="预计学习时长(分钟)"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="是否发布"),
                ),
                ("view_count", models.IntegerField(default=0, verbose_name="浏览次数")),
                ("like_count", models.IntegerField(default=0, verbose_name="点赞数")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="courses.course",
                        verbose_name="所属课程",
                    ),
                ),
            ],
            options={
                "verbose_name": "课程课时",
                "verbose_name_plural": "课程课时",
                "ordering": ["course", "day_number"],
                "unique_together": {("course", "day_number")},
            },
        ),
        migrations.CreateModel(
            name="UserNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="笔记内容")),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="是否公开"),
                ),
                ("like_count", models.IntegerField(default=0, verbose_name="点赞数")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="courses.lesson",
                        verbose_name="课时",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "学习笔记",
                "verbose_name_plural": "学习笔记",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LessonResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="资源标题")),
                (
                    "file",
                    models.FileField(
                        upload_to="lessons/resources/", verbose_name="资源文件"
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("code", "代码文件"),
                            ("pdf", "PDF文档"),
                            ("image", "图片"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="文件类型",
                    ),
                ),
                (
                    "file_size",
                    models.IntegerField(default=0, verbose_name="文件大小(字节)"),
                ),
                (
                    "download_count",
                    models.IntegerField(default=0, verbose_name="下载次数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="courses.lesson",
                        verbose_name="所属课时",
                    ),
                ),
            ],
            options={
                "verbose_name": "课程资源",
                "verbose_name_plural": "课程资源",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="course",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="courses.coursecategory",
                verbose_name="所属分类",
            ),
        ),
        migrations.CreateModel(
            name="AIConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("ollama_local", "Ollama本地"),
                            ("ollama_remote", "Ollama远程"),
                            ("deepseek", "DeepSeek"),
                            ("openai", "OpenAI"),
                        ],
                        default="ollama_local",
                        max_length=50,
                        verbose_name="AI服务提供商",
                    ),
                ),
                (
                    "api_endpoint",
                    models.URLField(
                        default="http://localhost:11434", verbose_name="API端点"
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="API密钥"
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        default="llama2", max_length=100, verbose_name="模型名称"
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(default=0.7, verbose_name="温度参数"),
                ),
                (
                    "max_tokens",
                    models.IntegerField(default=2000, verbose_name="最大tokens"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_config",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI配置",
                "verbose_name_plural": "AI配置",
            },
        ),
        migrations.CreateModel(
            name="UserProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "未开始"),
                            ("in_progress", "学习中"),
                            ("completed", "已完成"),
                        ],
                        default="not_started",
                        max_length=20,
                        verbose_name="学习状态",
                    ),
                ),
                (
                    "progress_percentage",
                    models.IntegerField(default=0, verbose_name="完成百分比"),
                ),
                (
                    "study_time",
                    models.IntegerField(default=0, verbose_name="学习时长(分钟)"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始学习时间"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "last_accessed",
                    models.DateTimeField(auto_now=True, verbose_name="最后访问时间"),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progress",
                        to="courses.lesson",
                        verbose_name="课时",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_progress",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "学习进度",
                "verbose_name_plural": "学习进度",
                "ordering": ["-last_accessed"],
                "unique_together": {("user", "lesson")},
            },
        ),
        migrations.CreateModel(
            name="ChatHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="会话ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "用户"),
                            ("assistant", "助手"),
                            ("system", "系统"),
                        ],
                        max_length=20,
                        verbose_name="角色",
                    ),
                ),
                ("content", models.TextField(verbose_name="消息内容")),
                (
                    "context",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="上下文信息"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_history",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "聊天历史",
                "verbose_name_plural": "聊天历史",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "session_id", "created_at"],
                        name="courses_cha_user_id_d93f61_idx",
                    )
                ],
            },
        ),
    ]
